force-app/main/default/objects/Related_Agreement__c/Related_Agreement__c.object-meta.xml
<CustomObject>
    <label>Related Agreement</label>
    <nameField>
        <label>Related Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Agreement__c/fields/Is_Commenced__c.field-meta.xml
<CustomField>
    <fullName>Is_Commenced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Commenced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/Rent_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Rent_Commencement_Date__c</fullName>
    <label>Rent Commencement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Partially Executed</fullName>
            </value>
            <value>
                <fullName>Pending Internal Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Fully Executed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HT_IsCommencedUpdateBatch.cls
global class HT_IsCommencedUpdateBatch  implements Schedulable,Database.Batchable<SObject>{
    string stringQuery;
    global HT_IsCommencedUpdateBatch(String query){
        stringQuery = query;
    }
    
    global void execute(SchedulableContext ctx){        
        Database.executeBatch(new HT_IsCommencedUpdateBatch(stringQuery));        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
       /* string stringQuery = 'SELECT Id,Is_Commenced__c FROM Related_Agreement__c WHERE Status__c = \'Fully Executed\''+
            ' AND Rent_Commencement_Date__c = TODAY AND Is_Commenced__c = FALSE';*/
        return Database.getQueryLocator(stringQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        for(SObject singleRecord : scope){
            singleRecord.put('Is_Commenced__c',TRUE);            
        }   
        update scope;
    }
    global void finish(Database.BatchableContext BC) {

    }

}