force-app/main/default/objects/Unit_Economics__c/Unit_Economics__c.object-meta.xml
<CustomObject>
    <label>Unit Economics</label>
    <nameField>
        <displayFormat>UE-{000000}</displayFormat>
        <label>Unit Economics Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Economics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Economics__c/fields/Approval_Process_Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Decision_Date__c</fullName>
    <label>Approval Process Decision Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Bulk Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/ChangedTotalCapex__c.field-meta.xml
<CustomField>
    <fullName>ChangedTotalCapex__c</fullName>
    <formula>(Total_Capex__c -  Easement_Acquisition__c ) - IF(isblank( Approval_Process_Approved_Capex__c ),0,Approval_Process_Approved_Capex__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Capex</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Latest_Unit_Economics__c.field-meta.xml
<CustomField>
    <fullName>Latest_Unit_Economics__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Latest Unit Economics</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Unit Economics</relationshipLabel>
    <relationshipName>Unit_Economics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HT_UnitEconomicsTriggerHandler.cls
public class HT_UnitEconomicsTriggerHandler {
    
   public static void executeBeforeInertTrigger(List<Unit_Economics__c> newList){
        List<Id> projectIdsList = new List<Id>();
   
        for(Unit_Economics__c singleRecord : newList){
            if(singleRecord.Latest_Unit_Economics__c == TRUE && singleRecord.Project__c != null){
                projectIdsList.add(singleRecord.Project__c);
            }            
        }
        
       if(!projectIdsList.isEmpty()) updateUEApprovedCheckbox(projectIdsList);
    }
    
    /*  public static void executeAfterInertTrigger(List<Unit_Economics__c> newList){
}*/
    
    public static void executeBeforeUpdateTrigger(List<Unit_Economics__c> newList, Map<Id,Unit_Economics__c>  oldMap){
        List<Id> projectIdsList = new List<Id>();
       
     
        for(Unit_Economics__c singleRecord : newList){
         //   Decimal IRRCompare = (singleRecord.X8_Year_IRR__c != null && singleRecord.Unlevered_IRR_w_Pipeline_Colo__c != null) ? 
   // (singleRecord.X8_Year_IRR__c > singleRecord.Unlevered_IRR_w_Pipeline_Colo__c ? singleRecord.X8_Year_IRR__c : singleRecord.Unlevered_IRR_w_Pipeline_Colo__c) :
    //(singleRecord.X8_Year_IRR__c != null ? singleRecord.X8_Year_IRR__c : (singleRecord.Unlevered_IRR_w_Pipeline_Colo__c != null ? singleRecord.Unlevered_IRR_w_Pipeline_Colo__c : 0));

            
           // decimal IRRCompare = Math.Max(singleRecord.X8_Year_IRR__c,singleRecord.Unlevered_IRR_w_Pipeline_Colo__c);
            // if(Math.Max(singleRecord.X8_Year_IRR__c,singleRecord.Unlevered_IRR_w_Pipeline_Colo__c) >=10 && singleRecord.ChangedTotalCapex__c <50000 && 
              if(( singleRecord.X8_Year_IRR__c  >=10) && singleRecord.ChangedTotalCapex__c <50000 && 
                singleRecord.Approval_Status__c !='Auto Approved' &&  singleRecord.Approval_Status__c !='Approved'){
                singleRecord.Approval_Status__c='Auto Approved';
                singleRecord.Approval_Process_Decision_Date__c = DateTime.Now();
                singleRecord.Latest_Unit_Economics__c = TRUE;                   
            }
            
            if (singleRecord.Approval_Status__c == 'Approved' && oldMap.get(singleRecord.Id).Approval_Status__c != 'Approved') {
                singleRecord.Approval_Process_Decision_Date__c = DateTime.Now();
                singleRecord.Latest_Unit_Economics__c = TRUE;  
            }              
            
           if(singleRecord.Latest_Unit_Economics__c == TRUE
             &&                singleRecord.Latest_Unit_Economics__c != oldMap.get(singleRecord.Id).Latest_Unit_Economics__c &&
               singleRecord.Project__c != null)
           
           {
                   projectIdsList.add(singleRecord.Project__c);
                  
               }           
        }
       if(!projectIdsList.isEmpty())  updateUEApprovedCheckbox(projectIdsList);
        
    }
    
    /*  public static void executeAfterUpdateTrigger(List<Unit_Economics__c> newList, Map<Id,Unit_Economics__c>  oldMap){

}*/
    
    
 /*   public static void updateUEApprovedCheckbox(List<Id> projectIdsList , Set<Id> newRecordIds) { 
        List<Unit_Economics__c> updateUEList = [SELECT Id, Latest_Unit_Economics__c FROM Unit_Economics__c 
                                                WHERE Latest_Unit_Economics__c=TRUE AND Project__c IN :projectIdsList  AND Id NOT IN :newRecordIds];
        
        for(Unit_Economics__c singleRecord : updateUEList){
            singleRecord.Latest_Unit_Economics__c = FALSE;
        }
        system.debug('Update UE List' + updateUEList);
        if(!updateUEList.isEmpty()){
            update updateUEList;
        }
        
    }*/
    
       public static void updateUEApprovedCheckbox(List<Id> projectIdsList ) { 
        List<Unit_Economics__c> updateUEList = [SELECT Id, Latest_Unit_Economics__c FROM Unit_Economics__c 
                                                WHERE Latest_Unit_Economics__c=TRUE AND Project__c IN :projectIdsList ];
        
        for(Unit_Economics__c singleRecord : updateUEList){
            singleRecord.Latest_Unit_Economics__c = FALSE;
        }
        system.debug('Update UE List' + updateUEList);
        if(!updateUEList.isEmpty()){
            update updateUEList;
        }
        
    }
    
}