force-app/main/default/objects/Site_Development_ABM_HNS__c/Site_Development_ABM_HNS__c.object-meta.xml
<CustomObject>
    <label>Site Development ABM HNS</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Development ABM HNS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Development_ABM_HNS__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Site Development ABM HNS</relationshipLabel>
    <relationshipName>Site_Development_ABM_HNS1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Development_ABM_HNS__c/fields/Site_Development_AT_T__c.field-meta.xml
<CustomField>
    <fullName>Site_Development_AT_T__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Development AT&amp;T</label>
    <referenceTo>Site_Development_AT_T__c</referenceTo>
    <relationshipLabel>Site Development ABM HNS</relationshipLabel>
    <relationshipName>Site_Development_ABM_HNS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Development_AT_T__c/Site_Development_AT_T__c.object-meta.xml
<CustomObject>
    <label>Site Development AT&amp;T</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Development AT&amp;T</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Development_AT_T__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Site Development AT&amp;T</relationshipLabel>
    <relationshipName>Site_Development_AT_T</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Development_AT_T__c/fields/Project_Template__c.field-meta.xml
<CustomField>
    <fullName>Project_Template__c</fullName>
    <formula>Project__r.strk__ProjectTemplate__r.Name</formula>
    <label>Project Template</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Development_AT_T__c/fields/Site_Development_ABM_HNS__c.field-meta.xml
<CustomField>
    <fullName>Site_Development_ABM_HNS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Development ABM HNS</label>
    <referenceTo>Site_Development_ABM_HNS__c</referenceTo>
    <relationshipLabel>Site Development AT&amp;T</relationshipLabel>
    <relationshipName>Site_Development_AT_T</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UnitiSiteDevelopmentHNSTriggerHandler.cls
/*************************************************************************************************
* SITETRACKER, INC. (“Sitetracker”) CONFIDENTIAL
* Unpublished Copyright (c) 2013-2022 SITETRACKER, INC., All Rights Reserved.
*
* NOTICE: All information contained herein is, and remains the property of Sitetracker.
* The intellectual and technical concepts contained herein are proprietary to Sitetracker and
* may be covered by U.S. and Foreign Patents, patents in process, and are protected by trade
* secret or copyright law.
*
* Dissemination of this information or reproduction of this material is strictly forbidden unless
* prior written permission is obtained from Sitetracker. Access to the source code contained
* herein is hereby forbidden to anyone except current Sitetracker employees, managers or
* contractors who have executed Confidentiality and Non-disclosure agreements explicitly
* covering such access.
*
* The copyright notice above does not evidence any actual or intended publication or disclosure
* of this source code, which includes information that is confidential and/or proprietary, and
* is a trade secret, of Sitetracker.
*
* @description UnitiSiteDevelopmentHNSTriggerHandler
*
*
* @author <A HREF="mailto:vsaran@sitetracker.com">Vartika Saran</A>
*
***************************************************************************************************/
global without sharing class UnitiSiteDevelopmentHNSTriggerHandler extends strk.StSubProjectExtendableTriggerHandler {
    private static final String SOBJECT_API = String.valueOf( Site_Development_ABM_HNS__c.SObjectType );
    private List<Site_Development_AT_T__c> attProjsToUpdate = new List<Site_Development_AT_T__c>();

    global virtual override void initializeExtended(String subProjectObjectName) {
    }

    global virtual override void bulkBeforeExtended() {
        if(Trigger.isInsert){
            //ST-00029566 : On creating AT&T project we auto create an ABM HNS project for certain criteria so linking the AT&T with the new HNS below
            Map<Id, Site_Development_ABM_HNS__c> projToHnsMap = new Map<Id, Site_Development_ABM_HNS__c>();

            for (Site_Development_ABM_HNS__c hnsProj : (List<Site_Development_ABM_HNS__c>) Trigger.new){
                if(hnsProj.Project_Template__c == Label.SITE_DEVELOPMENT_ABM_HNS_WITH_ATT_PROJECT_TEMPLATE){
                    projToHnsMap.put(hnsProj.Project__c, hnsProj);
                }
            }

            if(!projToHnsMap.isEmpty()){
                List<strk__Project__c> projList = [SELECT Site_Development_AT_T__c
                                                FROM strk__Project__c
                                                WHERE ID IN: projToHnsMap.keySet()];

                if(!projList.isEmpty()){
                    for(strk__Project__c proj : projList){
                        Site_Development_ABM_HNS__c hnsAbmProj = projToHnsMap.get(proj.Id);
                        hnsAbmProj.Site_Development_AT_T__c = proj.Site_Development_AT_T__c;
                    }
                }
            }
        }
    }

    global virtual override void bulkAfterExtended() {
        if(Trigger.isInsert){
            //ST-00029566 : Establishing connection 1:1 connection between AT&T and ABM HNS projects
            for (Site_Development_ABM_HNS__c hnsProj : (List<Site_Development_ABM_HNS__c>) Trigger.new){
                if(hnsProj.Site_Development_AT_T__c != null){
                    Site_Development_AT_T__c attProj = new Site_Development_AT_T__c();
                    attProj.Id = hnsProj.Site_Development_AT_T__c;
                    attProj.Site_Development_ABM_HNS__c = hnsProj.Id;
                    attProjsToUpdate.add(attProj);
                }
            }
        }
    }

    global virtual override void beforeInsertExtended( SObject so ){
    }

    global virtual override void beforeUpdateExtended(SObject oldSo, SObject newSo){
    }

    global virtual override void beforeDeleteExtended(SObject so) {
    }

    global virtual override void afterInsertExtended(SObject newSo) {
    }

    global virtual override void afterUpdateExtended(SObject oldSo, SObject newSo) {
    }

    global virtual override void afterDeleteExtended(SObject so) {
    }

    global virtual override void andFinallyExtended() {
        if(Trigger.isAfter && Trigger.isInsert && !attProjsToUpdate.isEmpty()){
            update attProjsToUpdate;
        }
    }

}