force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR 4)</booleanFilter>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>strk__Project__c.strk__Site__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Agreement_Type__c</field>
            <operation>equals</operation>
            <value>SDP</value>
        </filterItems>
        <filterItems>
            <field>strk__Project__c.strk__Project_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled, On Hold</value>
        </filterItems>
        <filterItems>
            <field>$Source.Agreement_Type__c</field>
            <operation>notEqual</operation>
            <value>SDP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>AgreementProjects</relationshipLabel>
    <relationshipName>AgreementProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Project_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Project_Acceptance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Acceptance(TBD)</label>
    <referenceTo>Project_Acceptance__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Rent_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Rent_Reduction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rent Reduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>AgreementSites</relationshipLabel>
    <relationshipName>AgreementSites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Site_ID__c</fullName>
    <formula>Site__r.Site_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/All_Agreement__c.object-meta.xml
<CustomObject>
    <label>All Agreement</label>
    <nameField>
        <displayFormat>AAGR-{000000000}</displayFormat>
        <label>All Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/All_Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>All Agreements</relationshipLabel>
    <relationshipName>All_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>All Agreements</relationshipLabel>
    <relationshipName>All_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/fields/Project_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Project_Acceptance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Acceptance</label>
    <referenceTo>Project_Acceptance__c</referenceTo>
    <relationshipLabel>All Agreements</relationshipLabel>
    <relationshipName>All_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/fields/Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Site_ID__c</fullName>
    <formula>IF(Agreement__c == null , Project__r.strk__Site__r.Site_ID__c, Agreement__r.Project__r.strk__Site__r.Site_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/Project_Acceptance__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Project Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Acceptance__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABM</fullName>
            </value>
            <value>
                <fullName>Easement &amp; Assignment Agreement</fullName>
            </value>
            <value>
                <fullName>Flood</fullName>
            </value>
            <value>
                <fullName>Flood 5.0</fullName>
            </value>
            <value>
                <fullName>Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>T-mobile</fullName>
            </value>
            <value>
                <fullName>Verizon</fullName>
            </value>
            <value>
                <fullName>Dish Networks</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>VzW HRR Indexed</fullName>
                <label>VzW HRR Indexed 4.25%</label>
            </value>
            <value>
                <fullName>AT&amp;T HRR Indexed</fullName>
            </value>
            <value>
                <fullName>T-Mobile BTSSA</fullName>
            </value>
            <value>
                <fullName>AT&amp;T BTS HRR New Offer Indexed 5%</fullName>
            </value>
            <value>
                <fullName>T-Mobile HRR Indexed 3.9%</fullName>
            </value>
            <value>
                <fullName>AT&amp;T BTS DDBTS Indexed 5%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Bulk Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/BD_Lead__c.field-meta.xml
<CustomField>
    <fullName>BD_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_BD_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collocation</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Lease Buyout</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Project Acceptances</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Project_Template__c.field-meta.xml
<CustomField>
    <fullName>Project_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Template</label>
    <referenceTo>strk__Project_Template__c</referenceTo>
    <relationshipLabel>Project Acceptances</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BTS</fullName>
            </value>
            <value>
                <fullName>BTS-P</fullName>
            </value>
            <value>
                <fullName>Combo (CMB)</fullName>
            </value>
            <value>
                <fullName>Corrective Maintenance (CM)</fullName>
            </value>
            <value>
                <fullName>Data Center (DC)</fullName>
            </value>
            <value>
                <fullName>DDBTS</fullName>
            </value>
            <value>
                <fullName>DDBTS-P</fullName>
            </value>
            <value>
                <fullName>Drop &amp; Swap</fullName>
            </value>
            <value>
                <fullName>Existing (EXT)</fullName>
            </value>
            <value>
                <fullName>Fiber (FR)</fullName>
            </value>
            <value>
                <fullName>Ground Only (GO)</fullName>
            </value>
            <value>
                <fullName>Harmoni Initiated</fullName>
            </value>
            <value>
                <fullName>Improvement (IMP)</fullName>
            </value>
            <value>
                <fullName>MKT</fullName>
            </value>
            <value>
                <fullName>New (NEW)</fullName>
                <default>true</default>
                <label>New (NEW)</label>
            </value>
            <value>
                <fullName>Other (OTH)</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance (PM)</fullName>
            </value>
            <value>
                <fullName>ROFR</fullName>
            </value>
            <value>
                <fullName>Structure &amp; Ground (SaG)</fullName>
            </value>
            <value>
                <fullName>Termination (TER)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Rent_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Rent_Reduction__c</fullName>
    <label>Rent Reduction %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Name</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>Project Acceptance</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Extension__c/Project_Extension__c.object-meta.xml
<CustomObject>
    <label>Project Extension</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Extension</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Extension__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Project Extension</relationshipLabel>
    <relationshipName>Project_Extension</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Extension__c/fields/Project_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Project_Acceptance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Acceptance</label>
    <referenceTo>Project_Acceptance__c</referenceTo>
    <relationshipLabel>Project Extension</relationshipLabel>
    <relationshipName>PE_Project_Acceptance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HT_AgreementBannerControllerTest.cls
@isTest
public class HT_AgreementBannerControllerTest {
	@TestSetup
	static void dataSetup(){
        strk__Site__c newSite = new strk__Site__c(
			Name = 'Test Site 123',
			Site_ID__c = 'TestSiteId',
            BD_Lead__c = Userinfo.getUserId()
		);
        insert newSite;
      
        
		strk__Project_Template__c testTemplate = new strk__Project_Template__c(
			strk__Active__c = true,
			Name = 'US Development'
		);
		insert new strk__Project_Template__c(
			strk__Active__c = true,
			Name = 'test template'
		);
		Database.insert( testTemplate );


		strk__Project__c testProject = new strk__Project__c(
			strk__Site__c = newSite.Id,
			strk__ProjectTemplate__c = testTemplate.Id,
			strk__Project_Status__c = '',
			strk__Project_Start_Date_F__c = System.today(),
			strk__Project_Type__c = 'ABM',
            Category__c = 'Collocation'
		);

		Database.insert( testProject );
		insert new Project_Extension__c(Project__c = testProject.Id);
           Project_Acceptance__c prjAcceptance = new Project_Acceptance__c();
        //prjAcceptance.Approval_Status__c = 'Auto Approved';
       // prjAcceptance.Category__c = 'Collocation';
       // prjAcceptance.Project_Type__c = 'Existing (EXT)';
        prjAcceptance.Total_Capex__c = 0;
        prjAcceptance.Project_Template__c = testTemplate.Id;
        prjAcceptance.Site__c = newSite.Id;
        prjAcceptance.Project__c = testProject.Id;
        insert prjAcceptance;
        
        insert new All_Agreement__c(Project__c = testProject.Id, Project_Acceptance__c = prjAcceptance.Id);
          Agreement__c newAgreement = new Agreement__c(Name=newSite.Site_ID__c+'_3', Site__c = newSite.Id, Project__c= testProject.Id, Rent_Reduction__c=true, Agreement_Type__c='Anchor',Ground_Interest__c='None');
        insert newAgreement;
           Agreement__c newAgreementGround = new Agreement__c(Name=newSite.Site_ID__c+'_1', Site__c = newSite.Id, Project__c= testProject.Id, HT_RevShare__c=true,  Agreement_Type__c='Ground',Ground_Interest__c='Lease');
        insert newAgreementGround;

           Agreement__c newAgreementColo = new Agreement__c(Name=newSite.Site_ID__c+'_4',Colocation_No__c='04', Site__c = newSite.Id, Project__c= testProject.Id,  Agreement_Type__c='Colocation',Ground_Interest__c='None');
        insert newAgreementColo;
 Agreement__c newAgreementColo5 = new Agreement__c(Name=newSite.Site_ID__c+'_5',Colocation_No__c='05', Site__c = newSite.Id, Project__c= testProject.Id,  Agreement_Type__c='Colocation',Ground_Interest__c='None');
        insert newAgreementColo5;

        
    }
    
	@isTest
    static void executeBeforeInsertTriggerTest(){
        Agreement__c newAgreement = [SELECT Id FROM Agreement__c WHERE Agreement_Type__c='Colocation' LIMIT 1];        
        HT_AgreementBannerController.getBannerMessage(newAgreement.Id);
        
    }
}