force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/FE_Date__c.field-meta.xml
<CustomField>
    <fullName>FE_Date__c</fullName>
    <label>FE Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Is_Commenced__c.field-meta.xml
<CustomField>
    <fullName>Is_Commenced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Commenced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR 4)</booleanFilter>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>strk__Project__c.strk__Site__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Agreement_Type__c</field>
            <operation>equals</operation>
            <value>SDP</value>
        </filterItems>
        <filterItems>
            <field>strk__Project__c.strk__Project_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled, On Hold</value>
        </filterItems>
        <filterItems>
            <field>$Source.Agreement_Type__c</field>
            <operation>notEqual</operation>
            <value>SDP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>AgreementProjects</relationshipLabel>
    <relationshipName>AgreementProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Project_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Project_Acceptance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Acceptance(TBD)</label>
    <referenceTo>Project_Acceptance__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Rent_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Rent_Commencement_Date__c</fullName>
    <label>Rent Commencement Date**</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/SDP_Active_Record__c.field-meta.xml
<CustomField>
    <fullName>SDP_Active_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SDP Active Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/All_Agreement__c.object-meta.xml
<CustomObject>
    <label>All Agreement</label>
    <nameField>
        <displayFormat>AAGR-{000000000}</displayFormat>
        <label>All Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/All_Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>All Agreements</relationshipLabel>
    <relationshipName>All_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>All Agreements</relationshipLabel>
    <relationshipName>All_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/fields/Project_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Project_Acceptance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Acceptance</label>
    <referenceTo>Project_Acceptance__c</referenceTo>
    <relationshipLabel>All Agreements</relationshipLabel>
    <relationshipName>All_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/All_Agreement__c/fields/Related_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Related_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Agreement</label>
    <referenceTo>Related_Agreement__c</referenceTo>
    <relationshipLabel>All Agreements</relationshipLabel>
    <relationshipName>All_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/Project_Acceptance__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Project Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Acceptance__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABM</fullName>
            </value>
            <value>
                <fullName>Easement &amp; Assignment Agreement</fullName>
            </value>
            <value>
                <fullName>Flood</fullName>
            </value>
            <value>
                <fullName>Flood 5.0</fullName>
            </value>
            <value>
                <fullName>Purchase Agreement</fullName>
            </value>
            <value>
                <fullName>T-mobile</fullName>
            </value>
            <value>
                <fullName>Verizon</fullName>
            </value>
            <value>
                <fullName>Dish Networks</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>VzW HRR Indexed</fullName>
                <label>VzW HRR Indexed 4.25%</label>
            </value>
            <value>
                <fullName>AT&amp;T HRR Indexed</fullName>
            </value>
            <value>
                <fullName>T-Mobile BTSSA</fullName>
            </value>
            <value>
                <fullName>AT&amp;T BTS HRR New Offer Indexed 5%</fullName>
            </value>
            <value>
                <fullName>T-Mobile HRR Indexed 3.9%</fullName>
            </value>
            <value>
                <fullName>AT&amp;T BTS DDBTS Indexed 5%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Project Acceptances</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/Related_Agreement__c.object-meta.xml
<CustomObject>
    <label>Related Agreement</label>
    <nameField>
        <label>Related Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>RelatedParentAgreements</relationshipLabel>
    <relationshipName>RelatedParentAgreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/FE_Date__c.field-meta.xml
<CustomField>
    <fullName>FE_Date__c</fullName>
    <label>Contract Fully Executed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/Is_Commenced__c.field-meta.xml
<CustomField>
    <fullName>Is_Commenced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Commenced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>strk__Project__c.strk__Site__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>strk__Project__c.strk__Project_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled, On Hold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>RelatedAgreementProjects</relationshipLabel>
    <relationshipName>RelatedAgreementProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/Project_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Project_Acceptance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Acceptance</label>
    <referenceTo>Project_Acceptance__c</referenceTo>
    <relationshipLabel>RelatedAgreementProjectAcceptances</relationshipLabel>
    <relationshipName>RelatedAgreementProjectAcceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/Rent_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Rent_Commencement_Date__c</fullName>
    <label>Rent Commencement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Related_Agreement__c/fields/SDP_Active_Record__c.field-meta.xml
<CustomField>
    <fullName>SDP_Active_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SDP Active Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HT_RelatedAgreementTriggerHandler.cls
public class HT_RelatedAgreementTriggerHandler {
    public static void executeBeforeInertTrigger(List<Related_Agreement__c> newList){
        
        List<Id> agreementIdsList = new List<Id>();
        
        for(Related_Agreement__c singleRecord : newList){
            if(singleRecord.FE_Date__c != null && singleRecord.Rent_Commencement_Date__c <= system.TODAY()){
                singleRecord.Is_Commenced__c = TRUE;
            }else{
                singleRecord.Is_Commenced__c = FALSE;
            }
            
            if(singleRecord.SDP_Active_Record__c == TRUE && singleRecord.Agreement__c != null){
                agreementIdsList.add(singleRecord.Agreement__c);
            }  
        }
        
       if(!agreementIdsList.isEmpty()) updateSDPActiveCheckbox(agreementIdsList);
    }
    public static void executeAfterInertTrigger(List<Related_Agreement__c> newList){
        List<Id> agreementIdsList = new List<Id>();        
        
        for(Related_Agreement__c singleRecord : newList){
            agreementIdsList.add(singleRecord.Agreement__c);
        }          
        processAllAgreementRecords(newList, agreementIdsList);
    }
    
    public static void executeBeforeUpdateTrigger(List<Related_Agreement__c> newList, Map<Id,Related_Agreement__c>  oldMap){
        
        List<Id> agreementIdsList = new List<Id>();
        
        for(Related_Agreement__c singleRecord : newList){
            if( (singleRecord.FE_Date__c != oldMap.get(singleRecord.Id).FE_Date__c ||
                 singleRecord.Rent_Commencement_Date__c != oldMap.get(singleRecord.Id).Rent_Commencement_Date__c)){
                     if(singleRecord.FE_Date__c != null && singleRecord.Rent_Commencement_Date__c <= system.TODAY()){
                          singleRecord.Is_Commenced__c = TRUE;
                     }else{
                         singleRecord.Is_Commenced__c = FALSE;
                     }               
                 }
            
            if(singleRecord.SDP_Active_Record__c == TRUE && singleRecord.Agreement__c != null){
                agreementIdsList.add(singleRecord.Agreement__c);
            } 
        }
        
        
       if(!agreementIdsList.isEmpty()) updateSDPActiveCheckbox(agreementIdsList);
    }
    
    public static void processAllAgreementRecords(List<Related_Agreement__c> newList, List<Id> agreementIdsList){
                     Map<Id, All_Agreement__c> allAgreementAgreementMap = new Map<Id, All_Agreement__c>();
        
        List<All_Agreement__c> upsertAllAgreementList = new List<All_Agreement__c>();
        List<All_Agreement__c> updatableAllAgreements = [SELECT Id, Project__c, Related_Agreement__c, Project_Acceptance__c, Agreement__c FROM All_Agreement__c
                                                         WHERE Agreement__c IN :agreementIdsList];
        
        for(All_Agreement__c singleRecord : updatableAllAgreements){
            system.debug(singleRecord);
            if( singleRecord.Agreement__c != null && ((allAgreementAgreementMap.containsKey(singleRecord.Agreement__c) && 
                allAgreementAgreementMap.get(singleRecord.Agreement__c).Related_Agreement__c != null) ||
               !allAgreementAgreementMap.containsKey(singleRecord.Agreement__c))){
                   allAgreementAgreementMap.put(singleRecord.Agreement__c, singleRecord);   
               }
        }
        
        for(Related_Agreement__c singleRecord : newList){
            if( singleRecord.Agreement__c != null && !allAgreementAgreementMap.keyset().isEmpty() &&
               allAgreementAgreementMap.containsKey(singleRecord.Agreement__c)){                      
                   All_Agreement__c allAgreementRecord = allAgreementAgreementMap.get(singleRecord.Agreement__c);
                   if(allAgreementRecord.Related_Agreement__c == NULL){
                       allAgreementRecord.Related_Agreement__c = singleRecord.Id;
                       upsertAllAgreementList.add(allAgreementRecord);
                   }else{
                       upsertAllAgreementList.add( HT_ProjectTriggerHandler.createAllAgreements(
                           new Map<String,Id>{'Project__c' => allAgreementRecord.Project__c,
                               'Project_Acceptance__c' => allAgreementRecord.Project_Acceptance__c,
                               'Agreement__c' => allAgreementRecord.Agreement__c,                                
                               'Related_Agreement__c' => singleRecord.Id}));
                       
                   }
               }            
        }
        
         if(!upsertAllAgreementList.isEmpty()){
            upsert upsertAllAgreementList;
        }
       
    }
    
      public static void updateSDPActiveCheckbox(List<Id> agreementIdList) { 
        List<Related_Agreement__c> updateRelatedAgreementList = [SELECT Id, SDP_Active_Record__c FROM Related_Agreement__c 
                                                WHERE SDP_Active_Record__c=TRUE AND Agreement__c IN :agreementIdList];
        
        for(Related_Agreement__c singleRecord : updateRelatedAgreementList){
            singleRecord.SDP_Active_Record__c = FALSE;
        }
        
        if(!updateRelatedAgreementList.isEmpty()){
            update updateRelatedAgreementList;
        }
        
    }
    
  
    
    
}