force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anchor</fullName>
            </value>
            <value>
                <fullName>Colocation</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>SDP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Contract_Fully_Executed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Fully_Executed__c</fullName>
    <label>Contract Fully Executed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/DD_Option_Current_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>DD_Option_Current_Expiration_Date__c</fullName>
    <label>DD/Option Current Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Ground_Interest__c.field-meta.xml
<CustomField>
    <fullName>Ground_Interest__c</fullName>
    <label>Ground Interest</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Agreement_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Easement (Day 1)</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR 4)</booleanFilter>
        <filterItems>
            <field>$Source.Site__c</field>
            <operation>equals</operation>
            <valueField>strk__Project__c.strk__Site__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Agreement_Type__c</field>
            <operation>equals</operation>
            <value>SDP</value>
        </filterItems>
        <filterItems>
            <field>strk__Project__c.strk__Project_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled, On Hold</value>
        </filterItems>
        <filterItems>
            <field>$Source.Agreement_Type__c</field>
            <operation>notEqual</operation>
            <value>SDP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>AgreementProjects</relationshipLabel>
    <relationshipName>AgreementProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>AgreementSites</relationshipLabel>
    <relationshipName>AgreementSites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Site_ID__c</fullName>
    <formula>Site__r.Site_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Internal Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Partially Executed</fullName>
            </value>
            <value>
                <fullName>Fully Executed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement__c/recordTypes/Agreement.recordType-meta.xml
<RecordType>
    <fullName>Agreement</fullName>
    <active>true</active>
    <label>Agreement</label>
</RecordType>

force-app/main/default/objects/Email_Alert_Settings__mdt/Email_Alert_Settings__mdt.object-meta.xml
<CustomObject>
    <description>CMT to store settings for email alerts</description>
    <label>Email Alert Setting</label>
    <pluralLabel>Email Alert Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_Alert_Settings__mdt/fields/Additional_Recipient_Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Additional_Recipient_Email_Addresses__c</fullName>
    <description>Field to store the comma-separated list of additional recipient email addresses</description>
    <inlineHelpText>Field to store the comma-separated list of additional recipient email addresses</inlineHelpText>
    <label>Additional Recipient Email Addresses</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Email_Alert_Settings__mdt/fields/Email_Template_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_API_Name__c</fullName>
    <description>Field to store email template API name.</description>
    <inlineHelpText>Field to store email template API name.</inlineHelpText>
    <label>Email Template API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Alert_Settings__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if alert is active</description>
    <inlineHelpText>True if alert is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_Alert_Settings__mdt/fields/Project_Recipient_Fields__c.field-meta.xml
<CustomField>
    <fullName>Project_Recipient_Fields__c</fullName>
    <description>Field to store the comma-separated list of users lookup on the related project which will be a recipient for email alerts</description>
    <inlineHelpText>Field to store the comma-separated list of users lookup on the related project which will be a recipient for email alerts</inlineHelpText>
    <label>Project Recipient Fields</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Email_Alert_Settings__mdt/fields/Reminder_Alert_Days__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Alert_Days__c</fullName>
    <description>Field to store reminder alert days when email alerts should go out</description>
    <inlineHelpText>Field to store reminder alert days when email alerts should go out</inlineHelpText>
    <label>Reminder Alert Days</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>180</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HT_AgreementDueDiligenceDateReminderTest.cls
/*************************************************************************************************
 * SITETRACKER, INC. (“Sitetracker”) CONFIDENTIAL
 * Unpublished Copyright (c) 2013-2024 SITETRACKER, INC., All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of Sitetracker.
 * The intellectual and technical concepts contained herein are proprietary to Sitetracker and
 * may be covered by U.S. and Foreign Patents, patents in process, and are protected by trade
 * secret or copyright law.
 *
 * Dissemination of this information or reproduction of this material is strictly forbidden unless
 * prior written permission is obtained from Sitetracker. Access to the source code contained
 * herein is hereby forbidden to anyone except current Sitetracker employees, managers or
 * contractors who have executed Confidentiality and Non-disclosure agreements explicitly
 * covering such access.
 *
 * The copyright notice above does not evidence any actual or intended publication or disclosure
 * of this source code, which includes information that is confidential and/or proprietary, and
 * is a trade secret, of Sitetracker.
 *
 * @description HT_AgreementDueDiligenceDateReminderTest
 *
 * @author <A HREF="mailto:sjain@sitetracker.com">Shubham Jain</A>
 *
 ***************************************************************************************************/
@IsTest
public with sharing class HT_AgreementDueDiligenceDateReminderTest {
    @TestSetup
    static void setupTestData() {
        //Create test data
        strk__Site__c site = new strk__Site__c(
                Name = 'Test site',
                Site_ID__c = 'TestSiteId'
        );
        insert site;

        strk__Project_Template__c testTemplate = new strk__Project_Template__c(
                Name = 'Test Template',
                strk__Active__c = true
        );
        insert testTemplate;

        Profile[] profiles = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

        User user = new User(
                LastName = 'one',
                Username = Math.random() + 'one@example.com',
                Email = 'one@example.com',
                Alias = 'one',
                ProfileId = profiles[0].Id,
                TimeZoneSidKey = 'GMT',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US'
        );
        insert user;

        strk__Project__c project = new strk__Project__c(
                strk__Site__c = site.Id,
                strk__ProjectTemplate__c = testTemplate.Id,
                strk__Project_Type__c = 'Development',
                strk__Project_Manager__c = user.Id
        );
        insert project;

        // Create a test Contact record
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Admin Notification Contact', Email = 'readmin@harmonitowers.com');
        insert contact;

        List<Agreement__c> agreements = new List<Agreement__c>();

        for (Integer i = 12; i < 17; i++) {
            Agreement__c agreement = new Agreement__c();
            agreement.Agreement_Type__c = 'Ground';
            agreement.DD_Option_Current_Expiration_Date__c = System.today().addDays(i);
            agreement.Status__c = 'Draft';
            agreement.Site__c = site.Id;
            agreement.Contract_Fully_Executed__c = System.today();
            agreement.Project__c = project.Id;
            agreement.Ground_Interest__c = 'Purchase';
            agreements.add(agreement);
        }
        insert agreements;

    }

    @IsTest
    private static void testAgreementDueDiligenceDateReminderBatch() {
        Test.startTest();

        //Create a mock list of Custom Metadata Type (CMT) records
        List<Email_Alert_Settings__mdt> mockCMTData = new List<Email_Alert_Settings__mdt>{
                new Email_Alert_Settings__mdt(
                        Additional_Recipient_Email_Addresses__c = 'additional@example.com',
                        Email_Template_API_Name__c = 'Agreement_Due_Diligence_Reminder',
                        Reminder_Alert_Days__c = '2',
                        Is_Active__c = true,
                        Project_Recipient_Fields__c = 'Project_Manager__c,strk__Project_Manager__c'
                )
        };

        //Mock EmailTemplate
        EmailTemplate testTemplate = new EmailTemplate(
                DeveloperName = 'Agreement_Due_Diligence_Reminder',
                TemplateType = 'Text',
                Name = 'Test Template',
                Subject = 'Test Email Template',
                Body = 'This is a test email body.',
                FolderId = UserInfo.getUserId()
        );
        insert testTemplate;

        // Test.startTest();

        // Inject the mock CMT data into the batch class by using the setter method
        HT_AgreementDueDiligenceDateReminder batchClass = new HT_AgreementDueDiligenceDateReminder();
        batchClass.alertSettings = mockCMTData;

        //Execute the batch class
        Database.executeBatch(batchClass, 100);

        Test.stopTest();

        List<strk__Project__c> projects = [SELECT Id FROM strk__Project__c];
        System.assertEquals(1, projects.size(), 'Project record not exist');

        List<Agreement__c> agreements = [SELECT Id FROM Agreement__c];
        System.assertEquals(5, agreements.size(), 'Agreement records not exist');

    }
}