force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anchor</fullName>
            </value>
            <value>
                <fullName>Colocation</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>SDP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Commencement_Date__c</fullName>
    <label>Commencement/Exercise Option Date(TBD)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Ground_Interest__c.field-meta.xml
<CustomField>
    <fullName>Ground_Interest__c</fullName>
    <label>Ground Interest</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Agreement_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Easement (Day 1)</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Is_Commenced__c.field-meta.xml
<CustomField>
    <fullName>Is_Commenced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Commenced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>AgreementSites</relationshipLabel>
    <relationshipName>AgreementSites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Site_ID__c</fullName>
    <formula>Site__r.Site_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Internal Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Partially Executed</fullName>
            </value>
            <value>
                <fullName>Fully Executed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HT_IsCommencedUpdateBatchTest.cls
@isTest
public class HT_IsCommencedUpdateBatchTest {
    
    @TestSetup
    static void dataSetup(){
        strk__Site__c newSite = new strk__Site__c(
            Name = 'Test Site 123',
            Site_ID__c = 'TestSiteId',
            BD_Lead__c = Userinfo.getUserId()
        );
        insert newSite;
        Agreement__c newAgreement = new Agreement__c(Name=newSite.Site_ID__c+'_1', Site__c = newSite.Id,
                                                      Commencement_Date__c = system.TODAY(),
                                                      Status__c ='Fully Executed', Agreement_Type__c='Anchor',Ground_Interest__c='None');
        insert newAgreement;        
    }
    @isTest
    static void batchExecuteTest(){
        string stringQuery = 'SELECT Id,Is_Commenced__c FROM Agreement__c WHERE Status__c = \'Fully Executed\''+
            ' AND Commencement_Date__c <= TODAY';
        
        Test.startTest();
        Database.executeBatch(new HT_IsCommencedUpdateBatch(stringQuery));
        Test.stopTest();
    }    @isTest
    static void scheduleExecuteTest(){
        string stringQuery = 'SELECT Id,Is_Commenced__c FROM Agreement__c WHERE Status__c = \'Fully Executed\''+
            ' AND Commencement_Date__c <= TODAY';
        String sch = '0 0 23 * * ?';
        Test.startTest();
        system.Schedule('newJob', sch, new HT_IsCommencedUpdateBatch(stringQuery));
        Test.stopTest();
    }
}