force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anchor</fullName>
            </value>
            <value>
                <fullName>Colocation</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>SDP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/HT_RevShare__c.field-meta.xml
<CustomField>
    <fullName>HT_RevShare__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Revenue Share</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Rent_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Rent_Reduction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rent Reduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>AgreementSites</relationshipLabel>
    <relationshipName>AgreementSites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HT_RevShare__c/HT_RevShare__c.object-meta.xml
<CustomObject>
    <label>RevenueShare</label>
    <nameField>
        <label>HT_RevShare Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevenueShares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HT_AgreementBannerController.cls
public class HT_AgreementBannerController {
    
    @AuraEnabled(cacheable=true)
    public static string getBannerMessage(Id recordId){
        String returnValue ='';
        Agreement__c currentAgreementRecord = [SELECT Id, Site__c FROM Agreement__c WHERE Id=:recordId];
        
        List<Agreement__c> siteAgreementRecordsList = [SELECT Id,Name, Agreement_Type__c, HT_RevShare__c, Rent_Reduction__c
                                                       FROM Agreement__c WHERE Site__c=:currentAgreementRecord.Site__c AND 
                                                       ( (Agreement_Type__c='Ground' AND HT_RevShare__c = TRUE) OR 
                                                        ((Agreement_Type__c='Anchor' AND Rent_Reduction__c = TRUE))) Order by Agreement_Type__c DESC];
        Boolean isRentReductionfound = false;
        Boolean isRevSharefound = false;
        for(Agreement__c singleRecord : siteAgreementRecordsList){
            
            if(singleRecord.Agreement_Type__c=='Ground' && singleRecord.HT_RevShare__c && !isRevSharefound ){
                returnValue +='Revenue Share is Enabled: <a href="/'+ singleRecord.Id +'" target="_blank">'+ singleRecord.Name +'</a> <br /> ';
                isRevSharefound = true;
            }
            if(singleRecord.Agreement_Type__c=='Anchor' && singleRecord.Rent_Reduction__c  && !isRentReductionfound){
                returnValue +=' Rent Reduction is Enabled:   <a href="/'+ singleRecord.Id +'" target="_blank">'+ singleRecord.Name +'</a>';
                isRentReductionfound = true;
            }
            if(isRentReductionfound && isRevSharefound ){
                break;
            }
        }
        
        
        return returnValue;
    }
    
    
}