force-app/main/default/objects/Project_Extension__c/Project_Extension__c.object-meta.xml
<CustomObject>
    <label>Project Extension</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Extension</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Extension__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Project Extension</relationshipLabel>
    <relationshipName>Project_Extension</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HT_ProjectExtensionTriggerHandler.cls
global  without sharing class HT_ProjectExtensionTriggerHandler extends strk.StSubProjectExtendableTriggerHandler{

    public static List<Id> taskCreationProcessedIdList = new List<Id>();
    public static List<Task> insertingTaskList = new List<Task>(); 
    public strk.StNotificationEngine notificationEngine {get; set;}   
    public static final String objectName = 'Project_Extension__c';  
    global override void initializeExtended(String pSObjectName){
    }
    global override void bulkBeforeExtended(){
        if ( !Trigger.isDelete && notificationEngine == null) {           
            notificationEngine = new strk.StNotificationEngine();           
            notificationEngine.call('initialize', new Map<String, Object>{'objectType' => objectName, 'newRecords' => Trigger.new});       
        }   
    }
    global override void bulkAfterExtended(){
        if (!Trigger.isDelete && notificationEngine == null) {           
            notificationEngine = new strk.StNotificationEngine();           
            notificationEngine.call('initialize',    new Map<String, Object>{'objectType' => objectName, 'newRecords' =>  Trigger.new});       
        } 
    }
    global override void beforeInsertExtended(SObject pNewObj){
    }
    global override void afterInsertExtended(SObject pNewObj){
    }
    global override void beforeUpdateExtended(SObject pOldObj, SObject pNewObj){
       // if (!Test.isRunningTest()) {           
            notificationEngine.call('evaluateLogicBefore',  new Map<String, Object>{'objectType' => objectName, 'newRecord' => pNewObj, 'oldRecord' => pOldObj});       
      //  }  
    }
    global override void afterUpdateExtended(SObject pOldObj, SObject pNewObj){
        
       // if (!Test.isRunningTest()) {           
            notificationEngine.call('evaluateLogic', new Map<String, Object>{'objectType' => objectName, 'newRecord' => pNewObj, 'oldRecord' => pOldObj});       
      //  }             
        if(!taskCreationProcessedIdList.contains(pNewObj.Id)){
            List<Task> taskList =  HT_ProjectTriggerHandler.createTask( pNewObj, pOldObj, (Id) pNewObj.get('Project__c'));
            if(!taskList.isEmpty()){
                insertingTaskList.addAll(taskList);
                taskCreationProcessedIdList.add(pNewObj.Id);
            }
        }
    }
    global override void beforeDeleteExtended(SObject pNewObj){
    }
    global override void afterDeleteExtended(SObject pNewObj){
    }
    global override void andFinallyExtended(){
        if (Trigger.isAfter && !Trigger.isDelete) {           
            notificationEngine.call('andFinally', new Map<String, Object>());       
        } 
          if(!insertingTaskList.isEmpty()){
            insert insertingTaskList;
            insertingTaskList.clear();
        }
    }

}