force-app/main/default/objects/Project_Extension__c/Project_Extension__c.object-meta.xml
<CustomObject>
    <label>Project Extension</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Extension</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Extension__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Project Extension</relationshipLabel>
    <relationshipName>Project_Extension</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Extension__c/fields/Unit_Economics_Id__c.field-meta.xml
<CustomField>
    <fullName>Unit_Economics_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Economics Id</label>
    <referenceTo>Unit_Economics__c</referenceTo>
    <relationshipLabel>Project Extension</relationshipLabel>
    <relationshipName>PE_UnitEconomics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/Unit_Economics__c.object-meta.xml
<CustomObject>
    <label>Unit Economics</label>
    <nameField>
        <displayFormat>UE-{000000}</displayFormat>
        <label>Unit Economics Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Economics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Economics__c/fields/Latest_Approved__c.field-meta.xml
<CustomField>
    <fullName>Latest_Approved__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Latest Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Unit Economics</relationshipLabel>
    <relationshipName>Unit_Economics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Project_Extension__c.field-meta.xml
<CustomField>
    <fullName>Project_Extension__c</fullName>
    <formula>Project__r.Project_Extension__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Extension</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UnitEconomicsScheduler.cls
global class UnitEconomicsScheduler implements schedulable {
    global void execute(schedulableContext sc){
        //Query today's created/modified records
        List<Unit_Economics__c> ueList = [
            SELECT Id,Project__c,Hard_Capex__c,Latest_Approved__c
            FROM Unit_Economics__c
            WHERE(CreatedDate = TODAY OR LastModifiedDate = TODAY)
            AND Latest_Approved__c = TRUE
        ];
        //Prepare Map (ProjectId → Cost)
        Map<Id,Decimal>projectCostMap = new Map<Id, Decimal>();
         
        for(Unit_Economics__c ue : ueList){
            if(ue.Project__c !=null){
                projectCostMap.put(ue.Project__c, ue.Hard_Capex__c);
            }  
        }
        //	Query Projects With Extension
        List<strk__Project__c>projects = [
            SELECT Id, Budget_Cost__c,Project_Extension__c
            FROM strk__Project__c
            WHERE Id IN :projectCostMap.KeySet()
        ];
        //Map Extension → Unit Economics
        Map<Id,Id>ExtensionToUEMap =new Map<Id,Id>();
         for(strk__Project__c project : projects){
            if(project.Project_Extension__c != null){
                ExtensionToUEMap.put(
                    project.Project_Extension__c,
                    ExtensionToUEMap.get(project.Id)
                );
            }
        }
        //Get Extensions
        List<Project_Extension__c> ExtensionsToUpdate = [
            SELECT Id, Unit_Economics_Id__c
            FROM Project_Extension__c
            WHERE Id IN :ExtensionToUEMap.keySet()
        ];

        // Update Extension with Unit Economics
        for(Project_Extension__c extension : ExtensionsToUpdate){
            Extension.Unit_Economics_Id__c = ExtensionToUEMap.get(extension.Id);
        }
        //Update Records
        if(!ExtensionsToUpdate.isEmpty()){
            update ExtensionsToUpdate;
        }
    }
}