force-app/main/default/objects/Project_Acceptance__c/Project_Acceptance__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Project Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Acceptance__c/fields/Approval_Process_Template__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Process Template</label>
    <referenceTo>strk__Approval_Process_Template__c</referenceTo>
    <relationshipLabel>Project Acceptances</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Bulk Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Attorney__c.field-meta.xml
<CustomField>
    <fullName>Attorney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attorney</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_Attorney</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/BD_Lead__c.field-meta.xml
<CustomField>
    <fullName>BD_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_BD_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/BD_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>BD_Sr_Vice_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Sr. Vice President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_BDVP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Chief_Development_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Development_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Development Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_CDO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Chief_Executive_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Executive_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Executive Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Chief_Financial_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Financial_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Financial Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_CFO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Finance_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>Finance_Sr_Vice_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Sr. Vice President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_FVP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Project Acceptances</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/RUCA_Code__c.field-meta.xml
<CustomField>
    <fullName>RUCA_Code__c</fullName>
    <label>RUCA Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Name</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>Project Acceptance</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/Team_config__mdt.object-meta.xml
<CustomObject>
    <label>Team config</label>
    <pluralLabel>Team configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Team_config__mdt/fields/Attorney__c.field-meta.xml
<CustomField>
    <fullName>Attorney__c</fullName>
    <label>Attorney</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/BD_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>BD_Sr_Vice_President__c</fullName>
    <label>BD Sr. Vice President</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Chief_Development_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Development_Officer__c</fullName>
    <label>Chief Development Officer</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Chief_Executive_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Executive_Officer__c</fullName>
    <label>Chief Executive Officer</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Chief_Financial_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Financial_Officer__c</fullName>
    <label>Chief Financial Officer</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Finance_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>Finance_Sr_Vice_President__c</fullName>
    <label>Finance Sr. Vice President</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/Unit_Economics__c.object-meta.xml
<CustomObject>
    <label>Unit Economics</label>
    <nameField>
        <displayFormat>UE-{000000}</displayFormat>
        <label>Unit Economics Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Economics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Economics__c/fields/Approval_Process_Approved_Capex__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Approved_Capex__c</fullName>
    <label>Total Last Approved Capex</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Approval_Process_Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Decision_Date__c</fullName>
    <label>Approval Process Decision Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Approval_Process_Template__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Process Template</label>
    <referenceTo>strk__Approval_Process_Template__c</referenceTo>
    <relationshipLabel>Unit Economics</relationshipLabel>
    <relationshipName>Unit_Economics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Bulk Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Attorney__c.field-meta.xml
<CustomField>
    <fullName>Attorney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attorney</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Economics_Attorney</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/BD_Lead__c.field-meta.xml
<CustomField>
    <fullName>BD_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Economics_BD_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/BD_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>BD_Sr_Vice_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Sr. Vice President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Economics_BDVP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Chief_Development_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Development_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Development Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Economics_CDO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Chief_Executive_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Executive_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Executive Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Economics_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Chief_Financial_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Financial_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Financial Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Economics_CFO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Finance_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>Finance_Sr_Vice_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Sr. Vice President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Economics_FVP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>strk__Project__c</referenceTo>
    <relationshipLabel>Unit Economics</relationshipLabel>
    <relationshipName>Unit_Economics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Project_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Project_Acceptance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Acceptance</label>
    <referenceTo>Project_Acceptance__c</referenceTo>
    <relationshipLabel>Unit Economics</relationshipLabel>
    <relationshipName>Unit_Economics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Name</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>Unit Economics</relationshipLabel>
    <relationshipName>Unit_Economics4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Economics__c/fields/Total_Capex__c.field-meta.xml
<CustomField>
    <fullName>Total_Capex__c</fullName>
    <label>Total Capex</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HT_NewUEController.cls
public class HT_NewUEController {
    
    @AuraEnabled
    public static Id createUE (Id projectId)
    {
       
        strk__Project__c currentProject = [SELECT Id,strk__Site__c, strk__Site__r.BD_Lead__c, (SELECT Id FROM Unit_Economics__r WHERE Project_Acceptance__c = null) FROM strk__Project__c WHERE Id =:projectId];
        Unit_Economics__c newUE = new Unit_Economics__c(Project__c = currentProject.Id, Site__c = currentProject.strk__Site__c);
          newUE.BD_Lead__c = currentProject.strk__Site__r.BD_Lead__c;
         newUE.Version__c = currentProject.Unit_Economics__r == null ? 2: currentProject.Unit_Economics__r.size()+2;
        // newProjectAcceptanceRecord.RUCA_Code__c = currentSite.RUCA_Code__c;
        //  newProjectAcceptanceRecord.Classification__c = currentSite.RUCA_Description__c;
        Team_config__mdt teamDetails = Team_config__mdt.getInstance('New_Project_Acceptance_Team_config');
        if(teamDetails != null){
            newUE.Chief_Development_Officer__c =  teamDetails.Chief_Development_Officer__c;// '0058W00000D7AqsQAF';
            newUE.Chief_Executive_Officer__c = teamDetails.Chief_Executive_Officer__c;//'0058W00000D7AqsQAF';
            newUE.Chief_Financial_Officer__c =teamDetails.Chief_Financial_Officer__c;// '0058W00000D7AqsQAF';
            newUE.BD_Sr_Vice_President__c = teamDetails.BD_Sr_Vice_President__c;//'0058W00000D7AqsQAF';
            newUE.Finance_Sr_Vice_President__c = teamDetails.Finance_Sr_Vice_President__c;//'0058W00000D7AqsQAF';
            newUE.Attorney__c = teamDetails.Attorney__c;//'0058W00000D7AqsQAF';
        }
      
        
         // Fetch last approved CAPEX
            Unit_Economics__c lastApprovedCapex;
            List<Unit_Economics__c> results = [
                SELECT Total_Capex__c 
                FROM Unit_Economics__c 
                WHERE Project__r.Id =:projectId
                    AND ( Approval_Status__c = 'Approved' OR Approval_Status__c = 'Bulk Approved')
                  //  AND Approval_Process_Template__c != NULL
               ORDER BY Approval_Process_Decision_Date__c DESC
               LIMIT 1
            ];

        
               if (!results.isEmpty()) {
                   lastApprovedCapex = results[0];
                    system.debug('Determine last approved capex'+  lastApprovedCapex);
                newUE.Approval_Process_Approved_Capex__c = 
            (lastApprovedCapex != null && lastApprovedCapex.Total_Capex__c != null) 
            ? lastApprovedCapex.Total_Capex__c 
                    : 0;}
                
        insert newUE;
        return newUE.Id;
    }   
    
}