force-app/main/default/objects/Project_Acceptance__c/Project_Acceptance__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Project Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Acceptance__c/fields/Attorney__c.field-meta.xml
<CustomField>
    <fullName>Attorney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attorney</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_Attorney</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/BD_Lead__c.field-meta.xml
<CustomField>
    <fullName>BD_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_BD_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/BD_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>BD_Sr_Vice_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Sr. Vice President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_BDVP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Chief_Development_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Development_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Development Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_CDO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Chief_Executive_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Executive_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Executive Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_CEO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Chief_Financial_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Financial_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chief Financial Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_CFO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Finance_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>Finance_Sr_Vice_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Sr. Vice President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Acceptances_FVP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/RUCA_Code__c.field-meta.xml
<CustomField>
    <fullName>RUCA_Code__c</fullName>
    <label>RUCA Code</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Name</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>Project Acceptance</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/Team_config__mdt.object-meta.xml
<CustomObject>
    <label>Team config</label>
    <pluralLabel>Team configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Team_config__mdt/fields/Attorney__c.field-meta.xml
<CustomField>
    <fullName>Attorney__c</fullName>
    <label>Attorney</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/BD_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>BD_Sr_Vice_President__c</fullName>
    <label>BD Sr. Vice President</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Chief_Development_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Development_Officer__c</fullName>
    <label>Chief Development Officer</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Chief_Executive_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Executive_Officer__c</fullName>
    <label>Chief Executive Officer</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Chief_Financial_Officer__c.field-meta.xml
<CustomField>
    <fullName>Chief_Financial_Officer__c</fullName>
    <label>Chief Financial Officer</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_config__mdt/fields/Finance_Sr_Vice_President__c.field-meta.xml
<CustomField>
    <fullName>Finance_Sr_Vice_President__c</fullName>
    <label>Finance Sr. Vice President</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HT_NewProjectAcceptanceController.cls
public class HT_NewProjectAcceptanceController {
    
    @AuraEnabled
    public static Id createProjectAcceptance (Id siteId)
    {
        strk__Site__c currentSite = [SELECT Id,BD_Lead__c,RUCA_Code__c,RUCA_Description__c FROM strk__Site__c WHERE Id =:siteId];
        Project_Acceptance__c newProjectAcceptanceRecord = new Project_Acceptance__c(Site__c = currentSite.Id);
        newProjectAcceptanceRecord.BD_Lead__c = currentSite.BD_Lead__c;
        newProjectAcceptanceRecord.RUCA_Code__c = currentSite.RUCA_Code__c;
        newProjectAcceptanceRecord.Classification__c = currentSite.RUCA_Description__c;
        Team_config__mdt teamDetails = Team_config__mdt.getInstance('New_Project_Acceptance_Team_config');
        if(teamDetails != null){
            newProjectAcceptanceRecord.Chief_Development_Officer__c =  teamDetails.Chief_Development_Officer__c;// '0058W00000D7AqsQAF';
            newProjectAcceptanceRecord.Chief_Executive_Officer__c = teamDetails.Chief_Executive_Officer__c;//'0058W00000D7AqsQAF';
            newProjectAcceptanceRecord.Chief_Financial_Officer__c =teamDetails.Chief_Financial_Officer__c;// '0058W00000D7AqsQAF';
            newProjectAcceptanceRecord.BD_Sr_Vice_President__c = teamDetails.BD_Sr_Vice_President__c;//'0058W00000D7AqsQAF';
            newProjectAcceptanceRecord.Finance_Sr_Vice_President__c = teamDetails.Finance_Sr_Vice_President__c;//'0058W00000D7AqsQAF';
            newProjectAcceptanceRecord.Attorney__c = teamDetails.Attorney__c;//'0058W00000D7AqsQAF';
        }
        insert newProjectAcceptanceRecord;
        return newProjectAcceptanceRecord.Id;
    }    
}