force-app/main/default/objects/Project_Acceptance__c/Project_Acceptance__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Project Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Acceptance__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Auto Approved</fullName>
            </value>
            <value>
                <fullName>Bulk Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Collocation</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Lease Buyout</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Project_Template__c.field-meta.xml
<CustomField>
    <fullName>Project_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Template</label>
    <referenceTo>strk__Project_Template__c</referenceTo>
    <relationshipLabel>Project Acceptances</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BTS</fullName>
            </value>
            <value>
                <fullName>BTS-P</fullName>
            </value>
            <value>
                <fullName>Combo (CMB)</fullName>
            </value>
            <value>
                <fullName>Corrective Maintenance (CM)</fullName>
            </value>
            <value>
                <fullName>Data Center (DC)</fullName>
            </value>
            <value>
                <fullName>DDBTS</fullName>
            </value>
            <value>
                <fullName>DDBTS-P</fullName>
            </value>
            <value>
                <fullName>Drop &amp; Swap</fullName>
            </value>
            <value>
                <fullName>Existing (EXT)</fullName>
            </value>
            <value>
                <fullName>Fiber (FR)</fullName>
            </value>
            <value>
                <fullName>Ground Only (GO)</fullName>
            </value>
            <value>
                <fullName>Harmoni Initiated</fullName>
            </value>
            <value>
                <fullName>Improvement (IMP)</fullName>
            </value>
            <value>
                <fullName>MKT</fullName>
            </value>
            <value>
                <fullName>New (NEW)</fullName>
                <default>true</default>
                <label>New (NEW)</label>
            </value>
            <value>
                <fullName>Other (OTH)</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance (PM)</fullName>
            </value>
            <value>
                <fullName>ROFR</fullName>
            </value>
            <value>
                <fullName>Structure &amp; Ground (SaG)</fullName>
            </value>
            <value>
                <fullName>Termination (TER)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/SBO_accept_reject_F__c.field-meta.xml
<CustomField>
    <fullName>SBO_accept_reject_F__c</fullName>
    <label>Site Build Opportunity Accept/Reject (F)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/SD_Narrative__c.field-meta.xml
<CustomField>
    <fullName>SD_Narrative__c</fullName>
    <label>SD Narrative</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Acceptance__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Name</label>
    <referenceTo>strk__Site__c</referenceTo>
    <relationshipLabel>Project Acceptance</relationshipLabel>
    <relationshipName>Project_Acceptances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Development_AT_T__c/Site_Development_AT_T__c.object-meta.xml
<CustomObject>
    <label>Site Development AT&amp;T</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Development AT&amp;T</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Development_AT_T__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>Text(Project__r.Category__c)</formula>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Development_AT_T__c/fields/Project_Template__c.field-meta.xml
<CustomField>
    <fullName>Project_Template__c</fullName>
    <formula>Project__r.strk__ProjectTemplate__r.Name</formula>
    <label>Project Template</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Development_AT_T__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Project__r.strk__Site__c</formula>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HT_ProjectAcceptanceTriggerHandlerTest.cls
@IsTest
private class HT_ProjectAcceptanceTriggerHandlerTest {
     @IsTest
    static void HT_testCreateProjectAcceptance() {
        strk__Project_Template__c attTemplate = new strk__Project_Template__c(
            Name = Label.SITE_DEVELOPMENT_ATT_WITH_HNS_PROJECT_TEMPLATE,
            strk__Project_Extension_Objects__c = String.valueOf( Site_Development_AT_T__c.SObjectType ),
            strk__Active__c = true,
            strk__Category__c = Uniti_Constants.PROJECT_TEMP_CATEGORY_TOWERS
        );
        insert attTemplate;
        
        strk__Site__c site = new strk__Site__c(
            Name = 'Test site',
            Site_ID__c = 'TestSiteId'
        );
        insert site;
        
        Project_Acceptance__c prjAcceptance = new Project_Acceptance__c();
        //prjAcceptance.Approval_Status__c = 'Auto Approved';
        prjAcceptance.Category__c = 'Collocation';
        prjAcceptance.Project_Type__c = 'Existing (EXT)';
        prjAcceptance.Total_Capex__c = 0;
        prjAcceptance.Project_Template__c = attTemplate.Id;
        prjAcceptance.Site__c = site.Id;
        insert prjAcceptance;
       system.debug(HT_ProjectAcceptanceTriggerHandler.templateIdMap);
        
        Project_Acceptance__c prjAcceptance1 = new Project_Acceptance__c();
        prjAcceptance1.Approval_Status__c = 'New';
        prjAcceptance1.Project_Template__c = attTemplate.Id;
        prjAcceptance1.Site__c = site.Id;
        prjAcceptance1.Category__c = 'collocation';
        prjAcceptance1.Project_Type__c = 'Existing (EXT)';
        insert prjAcceptance1;
        prjAcceptance1.Approval_Status__c = 'Approved';
        update prjAcceptance1;
        
        Project_Acceptance__c prjAcceptance2 = new Project_Acceptance__c();
        prjAcceptance2.Approval_Status__c = 'New';
        prjAcceptance2.Project_Template__c = attTemplate.Id;
        prjAcceptance2.Site__c = site.Id;
        prjAcceptance2.Category__c = 'Development';
        prjAcceptance2.SD_Narrative__c ='test';
        prjAcceptance2.SBO_accept_reject_F__c = system.today();
        prjAcceptance2.Project_Type__c = 'Existing (EXT)';
        insert prjAcceptance2;
        prjAcceptance2.Approval_Status__c = 'Approved';
        update prjAcceptance2;
        
        Project_Acceptance__c prjAcceptanceDel = new Project_Acceptance__c();
        prjAcceptanceDel.Approval_Status__c = 'New';
        prjAcceptanceDel.Project_Template__c = attTemplate.Id;
        prjAcceptanceDel.Site__c = site.Id;
        insert prjAcceptanceDel;
        delete prjAcceptanceDel;
    }

}